### ISSUE TITLE
Interrupt timer causes screen to flash

### ISSUE THREAD

**Issue by btfiedler** [joshuasnyder/MatrixDisplay#7]
I'm still learning how and why interrupts are needed and how that relates to the screen refresh. As of now, the screen constantly blinks. If I set the timer interval to low, it crashes.

    timer = timerBegin(0, 5000, true);
    timerAttachInterrupt(timer, &display_updater, true);
    timerAlarmWrite(timer, 5000, true);
    timerAlarmEnable(timer);

**Comment by joshuasnyder** [comment]
Thanks for logging the issue Brian. A PR is currently in review to address this.
